# Generated by Django 5.1.4 on 2025-01-05 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymessages', '0002_customuser_address_customuser_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='category',
            field=models.CharField(choices=[('general', '一般'), ('tech', '科技'), ('life', '生活'), ('entertainment', '娛樂')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
